# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

covExp <- function(DTR, theta) {
    .Call('stdf_covExp', PACKAGE = 'stdf', DTR, theta)
}

covGauss <- function(DTR, theta) {
    .Call('stdf_covGauss', PACKAGE = 'stdf', DTR, theta)
}

covMat <- function(DTR, theta, nu) {
    .Call('stdf_covMat', PACKAGE = 'stdf', DTR, theta, nu)
}

dlogProfileCpp <- function(theta, DTR, Y, XTR, subsetStatic, PhiTime, LambEst) {
    .Call('stdf_dlogProfileCpp', PACKAGE = 'stdf', theta, DTR, Y, XTR, subsetStatic, PhiTime, LambEst)
}

dlogProfileCppH <- function(theta, DTR, Y, XTR, PhiTime, LambEst) {
    .Call('stdf_dlogProfileCppH', PACKAGE = 'stdf', theta, DTR, Y, XTR, PhiTime, LambEst)
}

logProfileCpp <- function(theta, DTR, Y, XTR, subsetStatic, PhiTime, LambEst) {
    .Call('stdf_logProfileCpp', PACKAGE = 'stdf', theta, DTR, Y, XTR, subsetStatic, PhiTime, LambEst)
}

logProfileCppH <- function(theta, DTR, Y, XTR, PhiTime, LambEst) {
    .Call('stdf_logProfileCppH', PACKAGE = 'stdf', theta, DTR, Y, XTR, PhiTime, LambEst)
}

