# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dlogProfileCpp <- function(theta, DTR, Y, XTR, subsetStatic, PhiTime, LambEst) {
    .Call('gfda_dlogProfileCpp', PACKAGE = 'gfda', theta, DTR, Y, XTR, subsetStatic, PhiTime, LambEst)
}

logProfileCpp <- function(theta, DTR, Y, XTR, subsetStatic, PhiTime, LambEst) {
    .Call('gfda_logProfileCpp', PACKAGE = 'gfda', theta, DTR, Y, XTR, subsetStatic, PhiTime, LambEst)
}

